I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script call
    a "We believe that you are the newest target of the serial killer known
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 361, in script
    m "Did I do it? Is he dead?"
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script call
    a "We believe that you are the newest target of the serial killer known
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 361, in script
    m "Did I do it? Is he dead?"
  File "/Users/martincc/Desktop/renpy-7.1.3-sdk/renpy/ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/martincc/Desktop/renpy-7.1.3-sdk/renpy/ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 7.1.3.1092
Project001 1.0
Thu Apr 18 23:25:35 2019
